### PR TITLE
1046-fe-packages-ui-fix-missing-avatar-in-cardprofile-molecule

### LINKED ISSUE #1046: [FE][PACKAGES/UI] Fix missing Avatar in CardProfile Molecule

### PR DESCRIPTION
**Pull request by marmorrei**
Closes #1046

### CODE REVIEW

File: packages/ui/src/components/molecules/CardProfile.tsx [hunk 1]
```diff
@@ -139,20 +131,25 @@ export const CardProfile: FC<TCardProfile> = ({
...
+      <Avatar src={userData.profilePicture} alt={userData.profilePictureAlt} />
+      <UserInfoWrapper justify="space-between" gap={dimensions.spacing.xxs}>
         <UsernameStyled as="h1">{userData.userName}</UsernameStyled>
         <TextStyled>{userData.userEmail}</TextStyled>
         <ButtonStyled outline onClick={logoutData.handleLogOut}>
           {logoutData.logoutMsg}{' '}
-          <img
+          <ImgStyled
             src={logoutData.img?.logoutIcon}
             alt={logoutData.img?.altLogout}
```
Comment (NataliaR-BCN) [inline packages/ui/src/components/molecules/CardProfile.tsx:147]: This img can be an Icon, maybe? 
I think Power Setting New fits: https://fonts.google.com/icons?selected=Material+Symbols+Outlined:power_settings_new:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=power

File: packages/ui/src/components/atoms/Avatar/index.tsx [hunk 2]
```diff
@@ -7,43 +7,44 @@ export type TAvatar = HTMLAttributes<HTMLDivElement> & {
...
-
 }
+
 export const Avatar: FC<TAvatar> = ({
   src = defaultAvatar,
   alt,
-  avatarCss = {
-    defaultAvatarCss
-  },
+  avatarCss = { ...defaultAvatarCss },
```
Comment (NataliaR-BCN) [inline packages/ui/src/components/atoms/Avatar/index.tsx:44]: Is there a reason for this change? Sorry, just trying to understand!

File: packages/ui/src/stories/molecules/cardprofile/index.stories.ts [hunk 3]
```diff
@@ -103,7 +103,7 @@ export const WithErrors: CardProfileStory = {
   args: {
     userData: {
       profilePicture: '',
```
Comment (NataliaR-BCN) [inline packages/ui/src/stories/molecules/cardprofile/index.stories.ts:105]: Should be `profilePicture: undefined`

File: packages/ui/src/components/atoms/Avatar/index.tsx (hunk 2 above)
Comment (marmorrei) [reply packages/ui/src/components/atoms/Avatar/index.tsx:44]: Without the spread operator wouldn't pass the styles for mobile in Storybook, that's why. Also, Prettier passed it to the same line.

File: packages/ui/src/components/molecules/CardProfile.tsx (hunk 1 above)
Comment (marmorrei) [reply packages/ui/src/components/molecules/CardProfile.tsx:147]: Yes, I will change it, but the actual icon that you say I will pass it in the correspondant organism, so that in CardProfile it is possible not to have icon for logout

File: packages/ui/src/components/atoms/Avatar/index.tsx (hunk 2 above)
Comment (NataliaR-BCN) [reply packages/ui/src/components/atoms/Avatar/index.tsx:44]: I didn't realize the default styles were not working, thanks!

File: packages/ui/src/components/molecules/CardProfile.tsx [hunk 4]
```diff
@@ -108,17 +106,19 @@ const CenteredCounter = styled(FlexBox)`
   }
 `
 
+const LogoutIconStyled = styled(Icon)``
```
Comment (NataliaR-BCN) [inline packages/ui/src/components/molecules/CardProfile.tsx:109]: If you don't apply any custom styles, does the simple icon not work?

Comment (marmorrei) [reply packages/ui/src/components/molecules/CardProfile.tsx:109]: I will check, I just automatically changed the names and didn't think on it...

**Review by NataliaR-BCN — APPROVED** [review]

**Review by kevinmamaqi — APPROVED** [review]
